version: '3'

services:
  db:
    image: postgres:11.2
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  redis:
    image: "redis"
  web:
    deploy:
      restart_policy:
        condition: on-failure
    build: .
    command: bash -c "python /code/manage.py migrate --noinput && python /code/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
  celery:
    build: .
    command: celery -A Project worker --loglevel=INFO
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
  celery-beat:
    build: .
    command: celery -A Project beat --loglevel=INFO
    volumes:
      - .:/code
    depends_on:
      - db
      - redis

volumes:
  postgres_data: